### ISSUE TITLE
Image Processing

### ISSUE THREAD

**Issue by xiaoxuegao499** [HiLab-git/COPLE-Net#1]
Hi taigw @taigw,

How can I process the image so that its intensity is normalized to [0,1] using window/level of 1500/-650? 
Could you please share the code?

Thank you for your help!

**Comment by taigw** [comment]
Hi @xiaoxuegao499 ,
   This is a quite simple image intensity transform. The window width/level of 1500/-650 means you map intensity of [-1400, 100] to [0, 1]. Intensity lower than -1400 will be mapped to 0.0 and intensity higher than 100 is mapped to 1.0. I believe you can implement it by yourself quickly.
