### ISSUE TITLE
TRAINING

### ISSUE THREAD

**Issue by massimilianoporzio** [HiLab-git/COPLE-Net#4]
Please I need help in training.
I have Nifti images of CT scans. What is the correct order of padding/resizing and random cropping? How to load a 3d volume and then trasnform it for coplenet?

**Comment by wang-yu-xuan** [comment]
hello, I find that there is not code about loss, could you upload it? thank you!

**Comment by taigw** [comment]
@wang-yu-xuan The noise-robust dice loss has been implemented here:
https://github.com/HiLab-git/PyMIC/blob/master/pymic/loss/seg/dice.py

**Comment by taigw** [comment]
> fti images of CT s

Training of Cople-Net was implemted with PyMIC: https://github.com/HiLab-git/PyMIC
You can follow these examples for using PyMIC for training and testing: https://github.com/HiLab-git/PyMIC_examples
Just replace UNet in the examples with Cople-Net
