### ISSUE TITLE
A problem occured when reading .nii.gz

### ISSUE THREAD

**Issue by wuwo007** [HiLab-git/COPLE-Net#5]
Dear @taigw ,
Thank you for sharing this helpfull project.
I have occured one problem when reading the DICOM CT volume (.nii.gz) and its labeled image(.nii.gz)。
In the train function of net_run_agent.py, when i run this sentence "labels_prob = self.convert_tensor_type(data['label_prob'])", the error "KeyError: 'label_prob'" appeared.
I have checked the loaded training data, there is a attribute named "label", but not "label_prob".
Could you please help me to solve this problem?
Is there some requirements for the input labeled images? Thanks!

**Comment by aatiqa-ghazali** [comment]
@wuwo007  use these transformations 👍 train_transform = [RandomCrop,Pad, LabelToProbability]

and for this add these parameters as well

LabelToProbability_class_num = 2
LabelToProbability_inverse   = False



in the configuration file

**Comment by wuwo007** [comment]
It works!  Thank you very much.
